aztec-scan/chicmoz

services/explorer-ui/src/routes/__root.tsx

fix: only show Tanstack Devtools in development

---

packages/message-registry/src/aztec.ts
packages/types/src/aztec/index.ts
services/aztec-listener/src/aztec/index.ts
services/aztec-listener/src/event-handler/index.ts
services/explorer-api/migrations/0001_breezy_mastermind.sql
services/explorer-api/migrations/meta/0001_snapshot.json
services/explorer-api/migrations/meta/_journal.json
services/explorer-api/src/cache/index.ts
services/explorer-api/src/database/controllers/aztec-chain-connection.ts
services/explorer-api/src/database/controllers/index.ts
services/explorer-api/src/database/index.ts
services/explorer-api/src/database/schema/aztec-chain-connection.ts
services/explorer-api/src/event-handler/index.ts
services/explorer-api/src/event-handler/on-aztec-connection-event.ts
services/explorer-api/src/health.ts
services/explorer-api/src/http-server/express-config.ts
services/explorer-api/src/http-server/index.ts
services/explorer-api/src/http-server/routes/controllers/inofficial.ts
services/explorer-api/src/http-server/routes/index.ts
services/explorer-api/src/message-bus/index.ts
services/explorer-api/src/start.ts
services/explorer-api/src/stop.ts

feat: add health- and aztecChainConnection-endpoints

---

services/explorer-ui/src/components/blocks/block-table-columns.tsx
services/explorer-ui/src/components/blocks/blocks-schema.ts
services/explorer-ui/src/components/tx-effects/tx-effects-columns.tsx
services/explorer-ui/src/pages/block-details/util.ts
services/explorer-ui/src/pages/block/util.ts
services/explorer-ui/src/pages/landing/util.ts
services/explorer-ui/src/pages/tx-effect-details/index.tsx
services/explorer-ui/src/pages/tx-effect-details/utils.ts

resolves: #135 
- shadow to tabs
- added FPA to appropriate fees
- removed `numTxs` display

feat: improvements to UI

---

services/explorer-ui/package.json
services/explorer-ui/src/assets/copy-icon.svg
services/explorer-ui/src/assets/index.ts
services/explorer-ui/src/assets/success-icon.svg
services/explorer-ui/src/components/copy-text.tsx
services/explorer-ui/src/components/info-display/key-value-row.tsx
services/explorer-ui/src/components/ui/sonner.tsx
services/explorer-ui/src/main.tsx
services/explorer-ui/src/pages/block-details/index.tsx
yarn.lock

now you can copy truncated strings

ui: copyable text

---

services/explorer-api/src/http-server/routes/controllers/contracts.ts
services/explorer-ui/src/components/contracts/classes/columns.tsx
services/explorer-ui/src/components/contracts/instances/columns.tsx
services/explorer-ui/src/components/contracts/utils.tsx
services/explorer-ui/src/components/copy-text.tsx
services/explorer-ui/src/components/info-display/key-value-row.tsx
services/explorer-ui/src/components/tx-effects/tx-effects-columns.tsx
services/explorer-ui/src/pages/contract-class-details/index.tsx
services/explorer-ui/src/pages/contract-instance-details/util.ts
services/explorer-ui/src/pages/tx-effect-details/utils.ts
services/explorer-ui/src/routeTree.gen.ts
services/explorer-ui/src/routes/__root.tsx
services/explorer-ui/src/routes/contracts/classes.$id.versions.$version.lazy.tsx

feat: view separate versions of class id

---

services/explorer-ui/src/components/header.tsx
services/explorer-ui/src/components/ui/input.tsx

ui: update header menu for mobile

---

services/explorer-ui/src/components/info-badge.tsx
services/explorer-ui/src/pages/block/index.tsx
services/explorer-ui/src/pages/contract/index.tsx
services/explorer-ui/src/pages/landing/index.tsx
services/explorer-ui/src/pages/tx-effect/index.tsx

instead of using flex now we use a grid 
closes #190

ui: widen top badges to match table badges

---

services/explorer-ui/src/components/header.tsx

ui: just show hamburger icon

---

services/explorer-ui/src/pages/tx-effect-details/index.tsx
services/explorer-ui/src/pages/tx-effect-details/tabs.tsx
services/explorer-ui/src/pages/tx-effect-details/utils.ts

ui: show selected tab

---

k8s/production/cert-manager/cert-production-issuer.yaml
k8s/production/cert-manager/cert-staging-issuer.yaml
k8s/production/cert-manager/ingress_nginx_svc.yaml
k8s/production/explorer-api/ingress.yaml
k8s/production/explorer-ui/ingress.yaml
k8s/production/skaffold.production.full.yaml
k8s/production/websocket-event-publisher/ingress.yaml

changed from chicmoz.info to aztecscout.xyz
closes #206

feature: Update public domain name 

---

services/explorer-ui/src/components/custom-tooltip.tsx
services/explorer-ui/src/components/info-display/key-value-row.tsx
services/explorer-ui/src/pages/contract-class-details/tabs.tsx
services/explorer-ui/src/pages/tx-effect-details/index.tsx
services/explorer-ui/src/pages/tx-effect-details/tabs.tsx

fix: error in console for txeffect button

---

README.md

fix: correctly spell "miscellaneous" and added helm install-instructions

---

services/explorer-ui/src/components/copy-text.tsx
services/explorer-ui/src/components/info-display/key-value-row.tsx
services/explorer-ui/src/lib/create-hash-string.ts
services/explorer-ui/src/pages/landing/index.tsx

fix: overflow for links on mobile

---

services/event-cannon/package.json
services/event-cannon/src/cannon/index.ts
services/event-cannon/src/cannon/pxe.ts
services/event-cannon/src/cannon/scenarios/utils/index.ts
services/event-cannon/src/environment.ts
yarn.lock

- live networks
- improved configs

feat: event-cannon refactor

---

k8s/common/assets/grafana/datasources.yaml
k8s/local/grafana/dashboards/sandbox_overview.yaml
k8s/local/grafana/datasources_secret.yaml
k8s/local/grafana/ingress.yaml
k8s/local/skaffold.only_grafana.yaml

feat: Grafana for local development

---

packages/contract-verification/src/artifact/is-token-artifact.ts
packages/contract-verification/src/types.ts
services/explorer-api/src/svcs/database/controllers/l2contract/get-contract-instance.ts
services/explorer-api/src/svcs/database/controllers/l2contract/get-contract-instances.ts
services/explorer-api/src/svcs/database/controllers/l2contract/get-registered-contract-class.ts
services/explorer-api/src/svcs/database/controllers/l2contract/utils.ts
services/explorer-api/src/svcs/http-server/routes/controllers/contract-instances.ts
services/explorer-ui/src/pages/contract-class-details/index.tsx
services/explorer-ui/src/pages/contract-instance-details/index.tsx
services/explorer-ui/src/pages/contract-instance-details/tabs-section.tsx
services/explorer-ui/src/pages/contract-instance-details/util.ts

also improved some other UI-stuff and fixed a bug with missing instances

feat: showing real verified deployment data for contract instances

---

services/ethereum-listener/src/network-client/client/index.ts
services/ethereum-listener/src/network-client/contracts/index.ts
services/ethereum-listener/src/svcs/database/controllers/heights.ts
services/explorer-api/src/events/received/on-block/contracts.ts
services/explorer-ui/src/pages/validators.tsx

Re-adding query for validators stake

---

k8s/local/aztec-listener/remote_devnet/deployment.yaml
k8s/local/ethereum-listener/remote_devnet/deployment.yaml
k8s/local/ethereum-listener/remote_devnet/postgres-config.yaml
k8s/local/explorer-api/remote_devnet/deployment.yaml
k8s/local/explorer-api/remote_devnet/ingress.yaml
k8s/local/explorer-api/remote_devnet/postgres-config.yaml
k8s/local/explorer-api/remote_devnet/service.yaml
k8s/local/explorer-api/skaffold.remote_devnet.yaml
k8s/local/explorer-ui/remote_devnet/deployment.yaml
k8s/local/explorer-ui/remote_devnet/ingress.yaml
k8s/local/explorer-ui/remote_devnet/service.yaml
k8s/local/explorer-ui/skaffold.remote_devnet.yaml
k8s/local/postgres/values.yaml
k8s/local/skaffold.remote_devnet.yaml
k8s/local/websocket-event-publisher/remote_devnet/deployment.yaml
k8s/local/websocket-event-publisher/remote_devnet/ingress.yaml
k8s/local/websocket-event-publisher/remote_devnet/service.yaml
k8s/local/websocket-event-publisher/skaffold.remote_devnet.yaml
services/explorer-ui/src/components/next-block-countdown.tsx
services/explorer-ui/src/components/tx-effects/tx-effects-table.tsx
services/explorer-ui/src/pages/landing/index.tsx
services/explorer-ui/src/pages/landing/tx-effect-table-landing.tsx

resolves: #314 
https://github.com/user-attachments/assets/8f78887c-ffec-4876-b87a-24985d367f65

block countdown, pending txs counter and skaffold for remote_devnet

---

packages/types/src/aztec/special.ts
services/explorer-api/src/svcs/database/controllers/l2TxEffect/get-tx-effect.ts
services/explorer-api/src/svcs/database/controllers/l2TxEffect/stats.ts
services/explorer-api/src/svcs/database/controllers/l2block/stats.ts
services/explorer-api/src/svcs/database/controllers/l2contract/get-contract-instance.ts
services/explorer-api/src/svcs/database/controllers/l2contract/get-contract-instances.ts
services/explorer-api/src/svcs/database/controllers/l2contract/stats.ts
services/explorer-api/src/svcs/database/controllers/l2contract/utils.ts
services/explorer-api/src/svcs/http-server/routes/controllers/blocks.ts
services/explorer-api/src/svcs/http-server/routes/index.ts
services/explorer-api/src/svcs/http-server/routes/paths_and_validation.ts
services/explorer-ui/src/api/block.ts
services/explorer-ui/src/components/orphaned-banner.tsx
services/explorer-ui/src/hooks/api/blocks.ts
services/explorer-ui/src/pages/block-details/index.tsx
services/explorer-ui/src/pages/contract-class-details/index.tsx
services/explorer-ui/src/pages/contract-instance-details/index.tsx
services/explorer-ui/src/pages/network-health/finalization-status-section.tsx
services/explorer-ui/src/pages/network-health/index.tsx
services/explorer-ui/src/pages/network-health/orphaned-blocks-section.tsx
services/explorer-ui/src/pages/network-health/reorg-section.tsx
services/explorer-ui/src/pages/tx-effect-details/index.tsx
services/explorer-ui/src/pages/tx-effect-details/utils.ts
services/explorer-ui/src/service/constants.ts

Orphan banners for tx-effects and contract instances/classes 

---

packages/types/src/aztec/l2Block.ts
services/explorer-api/migrations/0002_finalizationStatus-correctly-ordered.sql
services/explorer-api/migrations/meta/0002_snapshot.json
services/explorer-api/migrations/meta/_journal.json
services/explorer-ui/src/pages/network-health/finalization-status-section.tsx

changing finalization order

---

services/explorer-ui/src/components/block-countdown-progress.tsx
services/explorer-ui/src/hooks/useTabVisibility.ts
services/explorer-ui/src/hooks/websocket.ts
services/explorer-ui/src/hooks/websocket/index.ts
services/explorer-ui/src/hooks/websocket/message-callbacks.ts

improve websockets

---

services/explorer-ui/src/components/info-card.tsx
services/explorer-ui/src/pages/ecosystem/index.tsx

Improving ecosystem page with InfoCard

---

services/explorer-ui/src/components/block-status-badge.tsx
services/explorer-ui/src/components/contracts/classes/table.tsx
services/explorer-ui/src/components/contracts/instances/table.tsx
services/explorer-ui/src/components/formated-time-cell.tsx
services/explorer-ui/src/components/header/desktop-header.tsx
services/explorer-ui/src/components/header/header.tsx
services/explorer-ui/src/components/header/types.ts
services/explorer-ui/src/components/info-display/key-value-display.tsx
services/explorer-ui/src/components/info-display/key-value-row.tsx
services/explorer-ui/src/components/magic-dev-link.tsx
services/explorer-ui/src/components/pending-txs/pending-txs-table.tsx
services/explorer-ui/src/components/tx-effects/tx-effects-columns.tsx
services/explorer-ui/src/components/ui/tooltip.tsx
services/explorer-ui/src/pages/block-details/index.tsx
services/explorer-ui/src/pages/block-details/util.ts
services/explorer-ui/src/pages/contract-class-details/key-value-helpers.ts
services/explorer-ui/src/pages/contract/index.tsx
services/explorer-ui/src/pages/tx-effect-details/utils.ts

feat: add tooltips to guide users

---

services/explorer-ui/src/components/blocks/blocks-table.tsx
services/explorer-ui/src/components/data-table/data-table-pagination.tsx
services/explorer-ui/src/components/data-table/data-table.tsx
services/explorer-ui/src/components/pending-txs/pending-txs-table.tsx
services/explorer-ui/src/components/tx-effects/tx-effects-table.tsx
services/explorer-ui/src/components/ui/table.tsx
services/explorer-ui/src/pages/landing/index.tsx

feat: linking from the tables on landing page

---

services/explorer-api/src/svcs/database/controllers/l2/search.ts
services/explorer-api/src/svcs/http-server/routes/controllers/search.ts
services/explorer-api/src/svcs/http-server/routes/index.ts
services/explorer-api/src/svcs/http-server/routes/paths_and_validation.ts

feat: publicLogs search

---

services/explorer-ui/src/components/data-table/data-table-pagination.tsx
services/explorer-ui/src/components/data-table/data-table.tsx
services/explorer-ui/src/components/pending-txs/pending-txs-table.tsx
services/explorer-ui/src/pages/contract/index.tsx

fix: pagination controls are now properly configured for all tables

---

packages/types/src/aztec/l2Contract.ts
services/explorer-api/migrations/0007_chubby_gamora.sql
services/explorer-api/migrations/meta/0007_snapshot.json
services/explorer-api/migrations/meta/_journal.json
services/explorer-api/src/constants.ts
services/explorer-api/src/start.ts
services/explorer-api/src/svcs/database/controllers/l2contract/update.ts
services/explorer-api/src/svcs/database/schema/l2contract/index.ts
services/explorer-ui/src/components/info-display/key-value-row.tsx
services/explorer-ui/src/pages/contract-class-details/key-value-helpers.tsx

feat: store/display source code links (...that are manually added)

---

services/explorer-ui/src/components/header/desktop-burger-menu.tsx
services/explorer-ui/src/hooks/index.ts
services/explorer-ui/src/hooks/useClickOutside.ts

• Created useClickOutside hook for handling click outside behavior
• Updated desktop burger menu to close when clicking outside
• Exported useClickOutside hook for reusability

ux: Add click outside functionality to burger menu

---

services/explorer-ui/src/components/validators/validator-history-table.tsx
services/explorer-ui/src/pages/l1/validator-details.tsx

• Update starfrich link to include validator address parameter
• Pass attesterAddress prop through ValidatorHistoryTable component

fix: update link to starfrich

---

services/explorer-api/src/svcs/database/controllers/ui/tables.ts
services/explorer-ui/src/hooks/websocket/message-callbacks.ts

• Enhanced reorg detection logic in websocket message callbacks
• Fixed cache invalidation to properly handle blockchain reorganizations
• Added comprehensive query invalidation when reorgs are detected
• Improved edge case handling for empty data arrays

hotfix: Improve blockchain reorg detection and cache invalidation

---

services/aztec-listener/src/svcs/poller/network-client/index.ts

fix: correctly marking nodes with "connection timout error" as offline
